# Generated by Django 5.1 on 2024-08-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ManyToManyField(related_name='guests', to='event.event'),
        ),
    ]
