# Generated by Django 5.1 on 2024-08-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_remove_guest_event_guest_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
    ]
